module.exports =
[ [ 'version', '13' ],
  [ 'comment', '# buffer_compare.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# same buffers\n' ],
  [ 'comment', '# not same buffers\n' ],
  [ 'result', { id: 1, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# tests 2\n' ],
  [ 'comment', '# pass  2\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 2, ok: true, name: 'should not be equivalent' } ],
  [ 'comment', '# common.js\n' ],
  [ 'result',
    { id: 3, ok: true, name: 'test/buffer_compare.js' } ],
  [ 'result',
    { id: 4, ok: true, name: 'just setup, nothing relevant' } ],
  [ 'comment', '# consumer.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# basic.tap\n' ],
  [ 'result', { id: 5, ok: true, name: 'test/common.js' } ],
  [ 'comment', '# indent.tap\n' ],
  [ 'result', { id: 6, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# missing.tap\n' ],
  [ 'result', { id: 7, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# skip-all.tap\n' ],
  [ 'result', { id: 8, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# yamlish.tap\n' ],
  [ 'result', { id: 9, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# tests 5\n' ],
  [ 'comment', '# pass  5\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 10, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# debug-test.js\n' ],
  [ 'result', { id: 11, ok: true, name: 'test/consumer.js' } ],
  [ 'garbage', 'debug test\n' ],
  [ 'garbage', 't.plan=1\n' ],
  [ 'garbage', '\'Debugger listening on port 5858\\n\'\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# debug test\n' ],
  [ 'comment', '# tests 1\n' ],
  [ 'comment', '# pass  1\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 12, ok: true, name: 'Should output debugger message' } ],
  [ 'comment', '# deep-strict.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment',
    '# strictDeepEquals shouldn\'t care about key order\n' ],
  [ 'result', { id: 13, ok: true, name: 'test/debug-test.js' } ],
  [ 'comment',
    '# strictDeepEquals shouldn\'t care about key order recursively\n' ],
  [ 'result',
    { id: 14, ok: true, name: 'should be strictly equal' } ],
  [ 'comment',
    '# strictDeepEquals shoudn\'t care about key order (but still might)\n' ],
  [ 'result',
    { id: 15, ok: true, name: 'should be strictly equal' } ],
  [ 'comment', '# tests 3\n' ],
  [ 'comment', '# pass  3\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 16, ok: true, name: 'should be strictly equal' } ],
  [ 'comment', '# deep.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment',
    '# deepEquals shouldn\'t care about key order and types\n' ],
  [ 'result', { id: 17, ok: true, name: 'test/deep-strict.js' } ],
  [ 'comment',
    '# deepEquals shouldn\'t care about key order recursively and types\n' ],
  [ 'result', { id: 18, ok: true, name: 'should be equivalent' } ],
  [ 'comment',
    '# deepEquals shoudn\'t care about key order (but still might) and types\n' ],
  [ 'result', { id: 19, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# tests 3\n' ],
  [ 'comment', '# pass  3\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 20, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# executed.sh\n' ],
  [ 'result', { id: 21, ok: true, name: 'test/deep.js' } ],
  [ 'result',
    { id: 22,
      ok: true,
      name: 'File with executable bit should be executed' } ],
  [ 'comment', '# exit-code.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# exit code 1 when tap results show failure\n' ],
  [ 'comment', '# test exits 0, has failures\n' ],
  [ 'result', { id: 23, ok: true, name: 'test/executed.sh' } ],
  [ 'result', { id: 24, ok: true, name: 'should be equal' } ],
  [ 'comment', '# test exits 1, has failures\n' ],
  [ 'result', { id: 25, ok: true, name: 'should be equal' } ],
  [ 'result', { id: 26, ok: true, name: 'should be equal' } ],
  [ 'comment', '# test exits 1, has no failures\n' ],
  [ 'result', { id: 27, ok: true, name: 'should be equal' } ],
  [ 'result', { id: 28, ok: true, name: 'should be equal' } ],
  [ 'comment', '# successes exit 0\n' ],
  [ 'comment', '# test that does nothing, but exits 0\n' ],
  [ 'result', { id: 29, ok: true, name: 'should be equal' } ],
  [ 'result', { id: 30, ok: true, name: 'should be equal' } ],
  [ 'comment', '# test that succeeds, and exits 0\n' ],
  [ 'result', { id: 31, ok: true, name: 'should be equal' } ],
  [ 'result', { id: 32, ok: true, name: 'should be equal' } ],
  [ 'comment', '# tests 10\n' ],
  [ 'comment', '# pass  10\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 33, ok: true, name: 'should be equal' } ],
  [ 'comment', '# expose-gc-test.js\n' ],
  [ 'result', { id: 34, ok: true, name: 'test/exit-code.js' } ],
  [ 'garbage', 'gc test\n' ],
  [ 'garbage', 't.plan=1\n' ],
  [ 'garbage', 'assert gc does not exist\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# gc test when the gc isn\'t there\n' ],
  [ 'garbage', 'gc test\n' ],
  [ 'garbage', 't.plan=2\n' ],
  [ 'garbage', 'gc test using --gc\n' ],
  [ 'garbage', 't.plan=1\n' ],
  [ 'garbage', 'assert gc exists\n' ],
  [ 'garbage', 'gc test using --expose-gc\n' ],
  [ 'garbage', 't.plan=1\n' ],
  [ 'garbage', 'assert gc exists\n' ],
  [ 'comment', '# gc test when the gc should be there\n' ],
  [ 'comment', '# test for gc using --gc\n' ],
  [ 'result', { id: 35, ok: true, name: 'should be equal' } ],
  [ 'comment', '# test for gc using --expose-gc\n' ],
  [ 'result', { id: 36, ok: true, name: 'should be equal' } ],
  [ 'comment', '# cleanup\n' ],
  [ 'comment', '# tests 3\n' ],
  [ 'comment', '# pass  3\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 37, ok: true, name: 'should be equal' } ],
  [ 'comment', '# global-harness-async.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# outer\n' ],
  [ 'comment', '# inner 1\n' ],
  [ 'result',
    { id: 38, ok: true, name: 'test/expose-gc-test.js' } ],
  [ 'comment', '# inner 2\n' ],
  [ 'result', { id: 39, ok: true, name: '1-1' } ],
  [ 'comment', '# inner 3\n' ],
  [ 'result', { id: 40, ok: true, name: '2-1' } ],
  [ 'result', { id: 41, ok: true, name: '3-1' } ],
  [ 'comment', '# independent-timeouts.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# finishes in time\n' ],
  [ 'comment', '# finishes in time too\n' ],
  [ 'comment', '# tests 0\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 42, ok: true, name: 'test/global-harness-async.js' } ],
  [ 'comment', '# isolated-conf-test.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# one\n' ],
  [ 'result',
    { id: 43, ok: true, name: 'test/independent-timeouts.js' } ],
  [ 'result', { id: 44, ok: true, name: 'should be equal' } ],
  [ 'comment', '# two\n' ],
  [ 'result', { id: 45, ok: true, name: 'should be equal' } ],
  [ 'result', { id: 46, ok: true, name: 'should be equal' } ],
  [ 'comment', '# tests 4\n' ],
  [ 'comment', '# pass  4\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 47, ok: true, name: 'should be equal' } ],
  [ 'comment', '# meta-test.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# meta test\n' ],
  [ 'result',
    { id: 48, ok: true, name: 'test/isolated-conf-test.js' } ],
  [ 'result', { id: 49, ok: true, name: 'sanity check' } ],
  [ 'result', { id: 50, ok: true, name: 'not ok' } ],
  [ 'result', { id: 51, ok: true, name: 'total test count' } ],
  [ 'result', { id: 52, ok: true, name: 'tests passed' } ],
  [ 'result', { id: 53, ok: true, name: 'tests failed' } ],
  [ 'result', { id: 54, ok: true, name: 'ok is boolean' } ],
  [ 'result', { id: 55, ok: true, name: 'skip is number' } ],
  [ 'result', { id: 56, ok: true, name: 'results isa Results' } ],
  [ 'result', { id: 57, ok: true, name: 'test isa Test' } ],
  [ 'comment', '# tests 10\n' ],
  [ 'comment', '# pass  10\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 58, ok: true, name: 'test isa Harness' } ],
  [ 'comment', '# nested-async.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# Harness async test support\n' ],
  [ 'result', { id: 59, ok: true, name: 'test/meta-test.js' } ],
  [ 'comment', '# sync child B\n' ],
  [ 'comment', '# async grandchild A\n' ],
  [ 'result', { id: 60, ok: true, name: 'sync child A' } ],
  [ 'comment', '# async grandchild B\n' ],
  [ 'result', { id: 61, ok: true, name: '(unnamed assert)' } ],
  [ 'comment', '# async child\n' ],
  [ 'result', { id: 62, ok: true, name: '(unnamed assert)' } ],
  [ 'comment', '# sync grandchild in async child B\n' ],
  [ 'result',
    { id: 63, ok: true, name: 'sync grandchild in async child A' } ],
  [ 'comment', '# tests 5\n' ],
  [ 'comment', '# pass  5\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 64, ok: true, name: '(unnamed assert)' } ],
  [ 'comment', '# nested-test.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# parent\n' ],
  [ 'result', { id: 65, ok: true, name: 'test/nested-async.js' } ],
  [ 'comment', '# subtest\n' ],
  [ 'result', { id: 66, ok: true, name: 'p test' } ],
  [ 'comment', '# nested subtest\n' ],
  [ 'result', { id: 67, ok: true, name: 'ch test' } ],
  [ 'comment', '# another subtest\n' ],
  [ 'result', { id: 68, ok: true, name: 'grch test' } ],
  [ 'comment', '# tests 4\n' ],
  [ 'comment', '# pass  4\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 69, ok: true, name: 'ch test 2' } ],
  [ 'comment', '# non-tap-output.js\n' ],
  [ 'comment', '# everything is fine\n' ],
  [ 'comment', '# there are no errors\n' ],
  [ 'comment', '# this output is not haiku.\n' ],
  [ 'comment', '# is 8 ok?\n' ],
  [ 'result', { id: 70, ok: true, name: 'test/nested-test.js' } ],
  [ 'comment', '# but: nevertheless, here we are\n' ],
  [ 'comment', '# this: is indented\n' ],
  [ 'comment', '# and: it\n' ],
  [ 'comment', '# might: ~\n' ],
  [ 'comment', '# be: yaml?\n' ],
  [ 'result', { id: 71, ok: true, name: ', 8 can stay.' } ],
  [ 'result', { id: 72, ok: true, name: 'might be confusing' } ],
  [ 'result', { id: 73, ok: true, name: 'done now, exiting' } ],
  [ 'comment', '# not-executed.sh\n' ],
  [ 'comment', '# output-childtest-description.js\n' ],
  [ 'comment',
    '# /Users/isaacs/dev/js/tap/test/nested-tests-fixture.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# nested tests, parent and child pass\n' ],
  [ 'result',
    { id: 74, ok: true, name: 'test/non-tap-output.js' } ],
  [ 'result',
    { id: 75, ok: true, name: 'outputs parent description' } ],
  [ 'result',
    { id: 76, ok: true, name: 'outputs child description' } ],
  [ 'result',
    { id: 77,
      ok: true,
      name: 'outputs parent description before parent result' } ],
  [ 'result',
    { id: 78,
      ok: true,
      name: 'outputs parent result before child description' } ],
  [ 'comment', '# tests 5\n' ],
  [ 'comment', '# pass  5\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 79,
      ok: true,
      name: 'outputs child description before child result' } ],
  [ 'comment', '# result-trap.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# trap result\n' ],
  [ 'result',
    { id: 80,
      ok: true,
      name: 'test/output-childtest-description.js' } ],
  [ 'result', { id: 81, ok: true, name: 'should be equal' } ],
  [ 'comment', '# tests 2\n' ],
  [ 'comment', '# pass  2\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 82, ok: true, name: 'should be equal' } ],
  [ 'comment', '# segv.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# setup\n' ],
  [ 'result', { id: 83, ok: true, name: 'test/result-trap.js' } ],
  [ 'comment', '# segv\n' ],
  [ 'result', { id: 84, ok: true, name: 'compiled seg faulter' } ],
  [ 'result', { id: 85, ok: true, name: 'should be equivalent' } ],
  [ 'result', { id: 86, ok: true, name: 'should be equivalent' } ],
  [ 'result', { id: 87, ok: true, name: 'should be equivalent' } ],
  [ 'result', { id: 88, ok: true, name: 'should be equivalent' } ],
  [ 'result', { id: 89, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# cleanup\n' ],
  [ 'result', { id: 90, ok: true, name: 'should be equal' } ],
  [ 'comment', '# tests 8\n' ],
  [ 'comment', '# pass  8\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 91, ok: true, name: 'cleaned up' } ],
  [ 'comment', '# simple-harness-test-with-plan.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# trivial success\n' ],
  [ 'result', { id: 92, ok: true, name: 'test/segv.js' } ],
  [ 'comment', '# two tests\n' ],
  [ 'result', { id: 93, ok: true, name: 'it works' } ],
  [ 'result', { id: 94, ok: true, name: 'math should work' } ],
  [ 'comment', '# tests 3\n' ],
  [ 'comment', '# pass  3\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 95, ok: true, name: 'false should not be ok' } ],
  [ 'comment', '# simple-harness-test.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# trivial success\n' ],
  [ 'result',
    { id: 96,
      ok: true,
      name: 'test/simple-harness-test-with-plan.js' } ],
  [ 'comment', '# two tests\n' ],
  [ 'result', { id: 97, ok: true, name: 'it works' } ],
  [ 'result', { id: 98, ok: true, name: 'math should work' } ],
  [ 'comment', '# tests 3\n' ],
  [ 'comment', '# pass  3\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 99, ok: true, name: 'false should not be ok' } ],
  [ 'comment', '# test-assert-todo-skip.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# not much\n' ],
  [ 'result',
    { id: 100, ok: true, name: 'test/simple-harness-test.js' } ],
  [ 'result',
    { id: 101,
      ok: true,
      skip: true,
      explanation: 'skip it good',
      name: 'always passes' } ],
  [ 'result',
    { id: 102,
      ok: true,
      skip: true,
      explanation: 'always fails',
      name: 'false' } ],
  [ 'result',
    { id: 103,
      ok: true,
      todo: true,
      explanation: 'remove todo directive',
      name: 'bonus' } ],
  [ 'result',
    { id: 104,
      ok: true,
      todo: true,
      explanation: 'implement a thing',
      name: 'expected' } ],
  [ 'result',
    { id: 105,
      ok: true,
      skip: true,
      name: 'always passes without explanation' } ],
  [ 'result',
    { id: 106,
      ok: true,
      skip: true,
      name: 'false without explanation' } ],
  [ 'result',
    { id: 107,
      ok: true,
      todo: true,
      name: 'bonus without explanation' } ],
  [ 'comment', '# tests 8\n' ],
  [ 'comment', '# skip  4\n' ],
  [ 'comment', '# todo  4\n' ],
  [ 'result',
    { id: 108,
      ok: true,
      todo: true,
      name: 'expected without explanation' } ],
  [ 'comment', '# test-descriptions.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# captures test descriptions\n' ],
  [ 'result',
    { id: 109, ok: true, name: 'test/test-assert-todo-skip.js' } ],
  [ 'result', { id: 110, ok: true, name: 'exit cleanly' } ],
  [ 'result',
    { id: 111, ok: true, name: 'captures SKIP description' } ],
  [ 'result',
    { id: 112, ok: true, name: 'skip summary is not from file' } ],
  [ 'result',
    { id: 113, ok: true, name: 'todo summary is not from file' } ],
  [ 'result',
    { id: 114,
      ok: false,
      name: 'captures TODO description',
      diag: 
       { file: 'child_process.js',
         line: 707,
         column: 7,
         stack: 
          [ 'getCaller (/Users/isaacs/dev/js/tap/lib/tap-assert.js:439:17)\n',
            'Function.assert (/Users/isaacs/dev/js/tap/lib/tap-assert.js:21:16)\n',
            'Test._testAssert (/Users/isaacs/dev/js/tap/lib/tap-test.js:87:16)\n',
            '/Users/isaacs/dev/js/tap/test/test-descriptions.js:32:7\n',
            'ChildProcess.exithandler (child_process.js:707:7)\n',
            'emitTwo (events.js:87:13)\n',
            'ChildProcess.emit (events.js:169:7)\n',
            'maybeClose (child_process.js:984:16)\n',
            'Socket.<anonymous> (child_process.js:1153:11)\n',
            'emitOne (events.js:77:13)\n' ] } } ],
  [ 'result', { id: 115, ok: true, name: 'exit cleanly' } ],
  [ 'result',
    { id: 116, ok: true, name: 'captures SKIP description' } ],
  [ 'result',
    { id: 117, ok: true, name: 'skip summary is not in TAP output' } ],
  [ 'result',
    { id: 118, ok: true, name: 'todo summary is not in TAP output' } ],
  [ 'result',
    { id: 119,
      ok: false,
      name: 'captures TODO description',
      diag: 
       { file: 'child_process.js',
         line: 707,
         column: 7,
         stack: 
          [ 'getCaller (/Users/isaacs/dev/js/tap/lib/tap-assert.js:439:17)\n',
            'Function.assert (/Users/isaacs/dev/js/tap/lib/tap-assert.js:21:16)\n',
            'Test._testAssert (/Users/isaacs/dev/js/tap/lib/tap-test.js:87:16)\n',
            '/Users/isaacs/dev/js/tap/test/test-descriptions.js:18:7\n',
            'ChildProcess.exithandler (child_process.js:707:7)\n',
            'emitTwo (events.js:87:13)\n',
            'ChildProcess.emit (events.js:169:7)\n',
            'maybeClose (child_process.js:984:16)\n',
            'Process.ChildProcess._handle.onexit (child_process.js:1057:5)\n' ] } } ],
  [ 'result', { id: 120, ok: true, name: 'exit cleanly' } ],
  [ 'result',
    { id: 121,
      ok: false,
      name: 'summarizes skipped count',
      diag: 
       { file: 'child_process.js',
         line: 707,
         column: 7,
         stack: 
          [ 'getCaller (/Users/isaacs/dev/js/tap/lib/tap-assert.js:439:17)\n',
            'Function.assert (/Users/isaacs/dev/js/tap/lib/tap-assert.js:21:16)\n',
            'Test._testAssert (/Users/isaacs/dev/js/tap/lib/tap-test.js:87:16)\n',
            '/Users/isaacs/dev/js/tap/test/test-descriptions.js:23:7\n',
            'ChildProcess.exithandler (child_process.js:707:7)\n',
            'emitTwo (events.js:87:13)\n',
            'ChildProcess.emit (events.js:169:7)\n',
            'maybeClose (child_process.js:984:16)\n',
            'Process.ChildProcess._handle.onexit (child_process.js:1057:5)\n' ] } } ],
  [ 'result',
    { id: 122,
      ok: false,
      name: 'summarizes todo count',
      diag: 
       { file: 'child_process.js',
         line: 707,
         column: 7,
         stack: 
          [ 'getCaller (/Users/isaacs/dev/js/tap/lib/tap-assert.js:439:17)\n',
            'Function.assert (/Users/isaacs/dev/js/tap/lib/tap-assert.js:21:16)\n',
            'Test._testAssert (/Users/isaacs/dev/js/tap/lib/tap-test.js:87:16)\n',
            '/Users/isaacs/dev/js/tap/test/test-descriptions.js:24:7\n',
            'ChildProcess.exithandler (child_process.js:707:7)\n',
            'emitTwo (events.js:87:13)\n',
            'ChildProcess.emit (events.js:169:7)\n',
            'maybeClose (child_process.js:984:16)\n',
            'Process.ChildProcess._handle.onexit (child_process.js:1057:5)\n' ] } } ],
  [ 'comment', '# tests 13\n' ],
  [ 'comment', '# pass  9\n' ],
  [ 'comment', '# fail  4\n' ],
  [ 'result',
    { id: 123,
      ok: false,
      name: 'test/test-descriptions.js',
      diag: { exit: 1, command: '/usr/local/bin/iojs test-descriptions.js' } } ],
  [ 'comment', '# test-directives.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# captures test descriptions\n' ],
  [ 'comment', '# raw TAP > TAP consumer > TAP producer\n' ],
  [ 'result',
    { id: 124, ok: true, name: 'overall result is PASS' } ],
  [ 'result', { id: 125, ok: true, name: 'captures ok SKIP' } ],
  [ 'result',
    { id: 126, ok: true, name: 'captures not ok SKIP' } ],
  [ 'result',
    { id: 127, ok: true, name: 'skip summary not in TAP output' } ],
  [ 'result', { id: 128, ok: true, name: 'captures ok TODO' } ],
  [ 'result',
    { id: 129, ok: true, name: 'captures not ok TODO' } ],
  [ 'result',
    { id: 130, ok: true, name: 'todo summary is not in TAP output' } ],
  [ 'comment', '# raw TAP > TAP consumer > summary\n' ],
  [ 'result',
    { id: 131, ok: true, name: 'no ugly "undefined" in output' } ],
  [ 'result',
    { id: 132, ok: true, name: 'overall result is PASS' } ],
  [ 'result', { id: 133, ok: true, name: 'no SKIP in summary' } ],
  [ 'result',
    { id: 134, ok: true, name: 'skip summary is not in TAP output' } ],
  [ 'result', { id: 135, ok: true, name: 'no TODO in summary' } ],
  [ 'result',
    { id: 136, ok: true, name: 'todo summary is not in TAP output' } ],
  [ 'comment', '# TAP producer via require("tap")\n' ],
  [ 'result',
    { id: 137, ok: true, name: 'no ugly "undefined" in output' } ],
  [ 'result',
    { id: 138, ok: true, name: 'overall result is PASS' } ],
  [ 'result', { id: 139, ok: true, name: 'captures ok SKIP' } ],
  [ 'result',
    { id: 140, ok: true, name: 'captures not ok SKIP' } ],
  [ 'result',
    { id: 141, ok: true, name: 'skip summary not in TAP output' } ],
  [ 'result', { id: 142, ok: true, name: 'captures ok TODO' } ],
  [ 'result',
    { id: 143, ok: true, name: 'captures not ok TODO' } ],
  [ 'result',
    { id: 144, ok: true, name: 'todo summary is not in TAP output' } ],
  [ 'comment', '# tests 22\n' ],
  [ 'comment', '# pass  22\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 145, ok: true, name: 'no ugly "undefined" in output' } ],
  [ 'comment', '# test-skip.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'result',
    { id: 146, ok: true, name: 'test/test-directives.js' } ],
  [ 'comment', '# tests 1\n' ],
  [ 'comment', '# skip  1\n' ],
  [ 'result',
    { id: 147,
      ok: true,
      skip: true,
      name: 'does not count as failure' } ],
  [ 'comment', '# test-test.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# testing the test object\n' ],
  [ 'result', { id: 148, ok: true, name: 'test/test-skip.js' } ],
  [ 'result',
    { id: 149,
      ok: true,
      name: 'test object should be instanceof Test' } ],
  [ 'result',
    { id: 150,
      ok: true,
      name: 'test object should be instanceof Harness' } ],
  [ 'result',
    { id: 151,
      ok: true,
      name: 'test._Test should be the Test class' } ],
  [ 'result',
    { id: 152, ok: true, name: 'should have isNotDeepEqual method' } ],
  [ 'result',
    { id: 153,
      ok: true,
      name: 'isNotDeepEqual method should be a function' } ],
  [ 'result',
    { id: 154, ok: true, name: 'should have equals method' } ],
  [ 'result',
    { id: 155, ok: true, name: 'equals method should be a function' } ],
  [ 'result',
    { id: 156, ok: true, name: 'should have inequivalent method' } ],
  [ 'result',
    { id: 157,
      ok: true,
      name: 'inequivalent method should be a function' } ],
  [ 'result',
    { id: 158, ok: true, name: 'should have threw method' } ],
  [ 'result',
    { id: 159, ok: true, name: 'threw method should be a function' } ],
  [ 'result',
    { id: 160, ok: true, name: 'should have strictEqual method' } ],
  [ 'result',
    { id: 161,
      ok: true,
      name: 'strictEqual method should be a function' } ],
  [ 'result',
    { id: 162, ok: true, name: 'should have emit method' } ],
  [ 'result',
    { id: 163, ok: true, name: 'emit method should be a function' } ],
  [ 'result',
    { id: 164, ok: true, name: 'should have fail method' } ],
  [ 'result',
    { id: 165, ok: true, name: 'fail method should be a function' } ],
  [ 'result',
    { id: 166, ok: true, name: 'should have strictEquals method' } ],
  [ 'result',
    { id: 167,
      ok: true,
      name: 'strictEquals method should be a function' } ],
  [ 'result',
    { id: 168, ok: true, name: 'should have notLike method' } ],
  [ 'result',
    { id: 169,
      ok: true,
      name: 'notLike method should be a function' } ],
  [ 'result',
    { id: 170, ok: true, name: 'should have dissimilar method' } ],
  [ 'result',
    { id: 171,
      ok: true,
      name: 'dissimilar method should be a function' } ],
  [ 'result',
    { id: 172, ok: true, name: 'should have true method' } ],
  [ 'result',
    { id: 173, ok: true, name: 'true method should be a function' } ],
  [ 'result',
    { id: 174, ok: true, name: 'should have assert method' } ],
  [ 'result',
    { id: 175, ok: true, name: 'assert method should be a function' } ],
  [ 'result',
    { id: 176, ok: true, name: 'should have is method' } ],
  [ 'result',
    { id: 177, ok: true, name: 'is method should be a function' } ],
  [ 'result',
    { id: 178, ok: true, name: 'should have ok method' } ],
  [ 'result',
    { id: 179, ok: true, name: 'ok method should be a function' } ],
  [ 'result',
    { id: 180, ok: true, name: 'should have isEqual method' } ],
  [ 'result',
    { id: 181,
      ok: true,
      name: 'isEqual method should be a function' } ],
  [ 'result',
    { id: 182, ok: true, name: 'should have isDeeply method' } ],
  [ 'result',
    { id: 183,
      ok: true,
      name: 'isDeeply method should be a function' } ],
  [ 'result',
    { id: 184, ok: true, name: 'should have deepEqual method' } ],
  [ 'result',
    { id: 185,
      ok: true,
      name: 'deepEqual method should be a function' } ],
  [ 'result',
    { id: 186, ok: true, name: 'should have deepEquals method' } ],
  [ 'result',
    { id: 187,
      ok: true,
      name: 'deepEquals method should be a function' } ],
  [ 'result',
    { id: 188, ok: true, name: 'should have pass method' } ],
  [ 'result',
    { id: 189, ok: true, name: 'pass method should be a function' } ],
  [ 'result',
    { id: 190, ok: true, name: 'should have length method' } ],
  [ 'result',
    { id: 191, ok: true, name: 'length method should be a function' } ],
  [ 'result',
    { id: 192, ok: true, name: 'should have skip method' } ],
  [ 'result',
    { id: 193, ok: true, name: 'skip method should be a function' } ],
  [ 'result',
    { id: 194, ok: true, name: 'should have isNotEqual method' } ],
  [ 'result',
    { id: 195,
      ok: true,
      name: 'isNotEqual method should be a function' } ],
  [ 'result',
    { id: 196, ok: true, name: 'should have looseEquals method' } ],
  [ 'result',
    { id: 197,
      ok: true,
      name: 'looseEquals method should be a function' } ],
  [ 'result',
    { id: 198, ok: true, name: 'should have false method' } ],
  [ 'result',
    { id: 199, ok: true, name: 'false method should be a function' } ],
  [ 'result',
    { id: 200, ok: true, name: 'should have notDeeply method' } ],
  [ 'result',
    { id: 201,
      ok: true,
      name: 'notDeeply method should be a function' } ],
  [ 'result',
    { id: 202, ok: true, name: 'should have ifErr method' } ],
  [ 'result',
    { id: 203, ok: true, name: 'ifErr method should be a function' } ],
  [ 'result',
    { id: 204, ok: true, name: 'should have hasFields method' } ],
  [ 'result',
    { id: 205,
      ok: true,
      name: 'hasFields method should be a function' } ],
  [ 'result',
    { id: 206, ok: true, name: 'should have isNotDeeply method' } ],
  [ 'result',
    { id: 207,
      ok: true,
      name: 'isNotDeeply method should be a function' } ],
  [ 'result',
    { id: 208, ok: true, name: 'should have like method' } ],
  [ 'result',
    { id: 209, ok: true, name: 'like method should be a function' } ],
  [ 'result',
    { id: 210, ok: true, name: 'should have similar method' } ],
  [ 'result',
    { id: 211,
      ok: true,
      name: 'similar method should be a function' } ],
  [ 'result',
    { id: 212, ok: true, name: 'should have notOk method' } ],
  [ 'result',
    { id: 213, ok: true, name: 'notOk method should be a function' } ],
  [ 'result',
    { id: 214, ok: true, name: 'should have isDissimilar method' } ],
  [ 'result',
    { id: 215,
      ok: true,
      name: 'isDissimilar method should be a function' } ],
  [ 'result',
    { id: 216, ok: true, name: 'should have isEquivalent method' } ],
  [ 'result',
    { id: 217,
      ok: true,
      name: 'isEquivalent method should be a function' } ],
  [ 'result',
    { id: 218, ok: true, name: 'should have doesNotEqual method' } ],
  [ 'result',
    { id: 219,
      ok: true,
      name: 'doesNotEqual method should be a function' } ],
  [ 'result',
    { id: 220, ok: true, name: 'should have isSimilar method' } ],
  [ 'result',
    { id: 221,
      ok: true,
      name: 'isSimilar method should be a function' } ],
  [ 'result',
    { id: 222, ok: true, name: 'should have notDeepEqual method' } ],
  [ 'result',
    { id: 223,
      ok: true,
      name: 'notDeepEqual method should be a function' } ],
  [ 'result',
    { id: 224, ok: true, name: 'should have type method' } ],
  [ 'result',
    { id: 225, ok: true, name: 'type method should be a function' } ],
  [ 'result',
    { id: 226, ok: true, name: 'should have notok method' } ],
  [ 'result',
    { id: 227, ok: true, name: 'notok method should be a function' } ],
  [ 'result',
    { id: 228, ok: true, name: 'should have isInequivalent method' } ],
  [ 'result',
    { id: 229,
      ok: true,
      name: 'isInequivalent method should be a function' } ],
  [ 'result',
    { id: 230, ok: true, name: 'should have isNot method' } ],
  [ 'result',
    { id: 231, ok: true, name: 'isNot method should be a function' } ],
  [ 'result',
    { id: 232, ok: true, name: 'should have same method' } ],
  [ 'result',
    { id: 233, ok: true, name: 'same method should be a function' } ],
  [ 'result',
    { id: 234, ok: true, name: 'should have isInequal method' } ],
  [ 'result',
    { id: 235,
      ok: true,
      name: 'isInequal method should be a function' } ],
  [ 'result',
    { id: 236, ok: true, name: 'should have _endNice method' } ],
  [ 'result',
    { id: 237,
      ok: true,
      name: '_endNice method should be a function' } ],
  [ 'result',
    { id: 238, ok: true, name: 'should have ifError method' } ],
  [ 'result',
    { id: 239,
      ok: true,
      name: 'ifError method should be a function' } ],
  [ 'result',
    { id: 240, ok: true, name: 'should have iferror method' } ],
  [ 'result',
    { id: 241,
      ok: true,
      name: 'iferror method should be a function' } ],
  [ 'result',
    { id: 242, ok: true, name: 'should have clear method' } ],
  [ 'result',
    { id: 243, ok: true, name: 'clear method should be a function' } ],
  [ 'result',
    { id: 244, ok: true, name: 'should have has method' } ],
  [ 'result',
    { id: 245, ok: true, name: 'has method should be a function' } ],
  [ 'result',
    { id: 246, ok: true, name: 'should have not method' } ],
  [ 'result',
    { id: 247, ok: true, name: 'not method should be a function' } ],
  [ 'result',
    { id: 248, ok: true, name: 'should have timeout method' } ],
  [ 'result',
    { id: 249,
      ok: true,
      name: 'timeout method should be a function' } ],
  [ 'result',
    { id: 250, ok: true, name: 'should have notSimilar method' } ],
  [ 'result',
    { id: 251,
      ok: true,
      name: 'notSimilar method should be a function' } ],
  [ 'result',
    { id: 252, ok: true, name: 'should have isUnlike method' } ],
  [ 'result',
    { id: 253,
      ok: true,
      name: 'isUnlike method should be a function' } ],
  [ 'result',
    { id: 254, ok: true, name: 'should have notEquals method' } ],
  [ 'result',
    { id: 255,
      ok: true,
      name: 'notEquals method should be a function' } ],
  [ 'result',
    { id: 256, ok: true, name: 'should have unsimilar method' } ],
  [ 'result',
    { id: 257,
      ok: true,
      name: 'unsimilar method should be a function' } ],
  [ 'result',
    { id: 258, ok: true, name: 'should have result method' } ],
  [ 'result',
    { id: 259, ok: true, name: 'result method should be a function' } ],
  [ 'result',
    { id: 260, ok: true, name: 'should have doesNotThrow method' } ],
  [ 'result',
    { id: 261,
      ok: true,
      name: 'doesNotThrow method should be a function' } ],
  [ 'result',
    { id: 262, ok: true, name: 'should have error method' } ],
  [ 'result',
    { id: 263, ok: true, name: 'error method should be a function' } ],
  [ 'result',
    { id: 264, ok: true, name: 'should have constructor method' } ],
  [ 'result',
    { id: 265,
      ok: true,
      name: 'constructor method should be a function' } ],
  [ 'result',
    { id: 266, ok: true, name: 'should have notEqual method' } ],
  [ 'result',
    { id: 267,
      ok: true,
      name: 'notEqual method should be a function' } ],
  [ 'result',
    { id: 268, ok: true, name: 'should have throws method' } ],
  [ 'result',
    { id: 269, ok: true, name: 'throws method should be a function' } ],
  [ 'result',
    { id: 270, ok: true, name: 'should have isLike method' } ],
  [ 'result',
    { id: 271, ok: true, name: 'isLike method should be a function' } ],
  [ 'result',
    { id: 272, ok: true, name: 'should have isNotSimilar method' } ],
  [ 'result',
    { id: 273,
      ok: true,
      name: 'isNotSimilar method should be a function' } ],
  [ 'result',
    { id: 274, ok: true, name: 'should have isNotEquivalent method' } ],
  [ 'result',
    { id: 275,
      ok: true,
      name: 'isNotEquivalent method should be a function' } ],
  [ 'result',
    { id: 276, ok: true, name: 'should have inequal method' } ],
  [ 'result',
    { id: 277,
      ok: true,
      name: 'inequal method should be a function' } ],
  [ 'result',
    { id: 278, ok: true, name: 'should have notEquivalent method' } ],
  [ 'result',
    { id: 279,
      ok: true,
      name: 'notEquivalent method should be a function' } ],
  [ 'result',
    { id: 280, ok: true, name: 'should have isNotLike method' } ],
  [ 'result',
    { id: 281,
      ok: true,
      name: 'isNotLike method should be a function' } ],
  [ 'result',
    { id: 282, ok: true, name: 'should have equivalent method' } ],
  [ 'result',
    { id: 283,
      ok: true,
      name: 'equivalent method should be a function' } ],
  [ 'result',
    { id: 284, ok: true, name: 'should have looseEqual method' } ],
  [ 'result',
    { id: 285,
      ok: true,
      name: 'looseEqual method should be a function' } ],
  [ 'result',
    { id: 286, ok: true, name: 'should have equal method' } ],
  [ 'result',
    { id: 287, ok: true, name: 'equal method should be a function' } ],
  [ 'result',
    { id: 288, ok: true, name: 'should have unlike method' } ],
  [ 'result',
    { id: 289, ok: true, name: 'unlike method should be a function' } ],
  [ 'result',
    { id: 290, ok: true, name: 'should have doesNotHave method' } ],
  [ 'result',
    { id: 291,
      ok: true,
      name: 'doesNotHave method should be a function' } ],
  [ 'result',
    { id: 292, ok: true, name: 'should have comment method' } ],
  [ 'result',
    { id: 293,
      ok: true,
      name: 'comment method should be a function' } ],
  [ 'result',
    { id: 294, ok: true, name: 'should have isa method' } ],
  [ 'comment', '# tests 147\n' ],
  [ 'comment', '# pass  147\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 295, ok: true, name: 'isa method should be a function' } ],
  [ 'comment', '# timeout.js\n' ],
  [ 'result', { id: 296, ok: true, name: 'test/test-test.js' } ],
  [ 'garbage', 'timeout test\n' ],
  [ 'garbage', 't.plan=2\n' ],
  [ 'garbage', 'a assert\n' ],
  [ 'garbage', 'b assert\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# timeout test with plan only\n' ],
  [ 'result', { id: 297, ok: true, name: 'a' } ],
  [ 'garbage', 'timeout test\n' ],
  [ 'garbage', 't.plan=2\n' ],
  [ 'garbage', 'a assert\n' ],
  [ 'garbage', 'b assert\n' ],
  [ 'comment', '# timeout test with plan and end\n' ],
  [ 'result', { id: 298, ok: true, name: 'b' } ],
  [ 'result', { id: 299, ok: true, name: 'a' } ],
  [ 'comment', '# tests 4\n' ],
  [ 'comment', '# pass  4\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 300, ok: true, name: 'b' } ],
  [ 'comment', '# trivial-success.js\n' ],
  [ 'result', { id: 301, ok: true, name: 'test/timeout.js' } ],
  [ 'comment', '# undefined_indented.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# consume yaml\n' ],
  [ 'result',
    { id: 302, ok: true, name: 'test/trivial-success.js' } ],
  [ 'comment', '# tests 1\n' ],
  [ 'comment', '# pass  1\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result',
    { id: 303, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# valid-command.js\n' ],
  [ 'comment', '# TAP version 13\n' ],
  [ 'comment', '# valid command\n' ],
  [ 'result',
    { id: 304, ok: true, name: 'test/undefined_indented.js' } ],
  [ 'result',
    { id: 305, ok: true, name: 'should be equivalent' } ],
  [ 'result',
    { id: 306, ok: true, name: 'should be equivalent' } ],
  [ 'result',
    { id: 307, ok: true, name: 'should be equivalent' } ],
  [ 'result',
    { id: 308, ok: true, name: 'should be equivalent' } ],
  [ 'result',
    { id: 309, ok: true, name: 'should be equivalent' } ],
  [ 'comment', '# tests 6\n' ],
  [ 'comment', '# pass  6\n' ],
  [ 'comment', '# ok\n' ],
  [ 'result', { id: 310, ok: true, name: 'should be equal' } ],
  [ 'result',
    { id: 311, ok: true, name: 'test/valid-command.js' } ],
  [ 'plan', 311 ],
  [ 'comment', '# tests 311\n' ],
  [ 'comment', '# pass  297\n' ],
  [ 'comment', '# fail  5\n' ],
  [ 'comment', '# skip  5\n' ],
  [ 'comment', '# todo  4\n' ],
  [ 'complete',
    { plan: 311,
      count: 311,
      pass: 306,
      ok: false,
      fail: 5,
      todo: 4,
      skip: 5 } ] ]
