const t = require('tap')
const yaml = require('../..')
const {create, Domain} = require('domain')
const o = { domainy: create() }
const s1 = yaml.stringify(o)
t.matchSnapshot(s1, 'first stringify')
const p1 = yaml.parse(s1)
const s2 = yaml.stringify(p1)
t.equal(s2, s1, 'second stringify matches first')
t.type(p1.domainy, Domain, 'parsed has a domain object')
